:concurrency: 2
:queues:
  - default
  - mailers
  - low

:schedule:
  import_advisories_from_rubysec_db:
    every: '10m'
    class: Advisories::ImportWorker
    queue: low
    description: 'Import new advisories from rubysec-database'